---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
        - name: frontend
          image: ahsatout/frontend:1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: qr-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
