apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qr-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/ahsatout/qr-code-devops-project.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: qr-code-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
