name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "front-end-nextjs/**"
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - "front-end-nextjs/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push API image
        if: contains(github.event.head_commit.message, 'api') || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/api:buildcache,mode=max

      - name: Build and push Front-end image
        if: contains(github.event.head_commit.message, 'frontend') || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v4
        with:
          context: ./front-end-nextjs
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/front-end:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/front-end:buildcache,mode=max
