name: CI/CD Pipeline for API

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "api/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push API image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api:${IMAGE_TAG} ./api
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api:${IMAGE_TAG}

      - name: Update API image tag in Kubernetes manifest
        run: |
          sed -i "s|image: .*/api:.*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/api:${{ github.run_number }}|" ./k8s/api-deployment.yaml

      - name: Commit and push updated API manifest
        run: |
          git config --global user.name "Abdelhakim Satout"
          git config --global user.email "hakim.satout@gmail.com"
          git add ./k8s/api-deployment.yaml
          git commit -m "Update API image tag to ${{ github.run_number }}"
          git push origin main
